import { useState } from "react";
import { createPortal } from "react-dom";
import { useOutletContext } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { MessageCircle, Plus, Play, GripVertical, Pencil, Trash2, X, Copy, Check } from "lucide-react";
import type { Paciente, Exercicio } from "../types";
import { buildPlanWhatsAppText } from "../lib/whatsapp";
import "./PlanoTratamento.css";

const CATEGORIA_COLORS: Record<string, string> = {
  Fortalecimento: "#E04F5F",
  Estabilização: "#007AFF",
  Flexibilidade: "#E8973A",
  Mobilidade: "#AF52DE",
  Funcional: "#34C759",
  Relaxamento: "#5AC8FA",
  Propriocepção: "#E8973A",
  Equilíbrio: "#007AFF",
};

/**
 * Modal displaying the WhatsApp-formatted treatment plan text with a copy button.
 *
 * Text is generated by {@link buildPlanWhatsAppText} from `src/lib/whatsapp.ts`.
 * Closes with a CSS transition (~180 ms) before invoking `onClose`.
 *
 * @param props.paciente - Patient whose plan is being shared (name + condition in header).
 * @param props.exercicios - Ordered exercise list included in the message.
 * @param props.onClose - Called after the close animation completes.
 * @returns A portal overlay with the formatted plan text and a clipboard copy button.
 */
function WhatsAppModal({ paciente, exercicios, onClose }: {
  paciente: Paciente;
  exercicios: Exercicio[];
  onClose: () => void;
}) {
  const { t } = useTranslation();
  const [closing, setClosing] = useState(false);
  const [copied, setCopied] = useState(false);
  const text = buildPlanWhatsAppText(paciente, exercicios);

  const handleClose = () => {
    setClosing(true);
    setTimeout(onClose, 180);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* fallback silent */
    }
  };

  return createPortal(
    <div
      className={`wa-modal-overlay${closing ? " closing" : ""}`}
      role="dialog"
      aria-modal="true"
      onMouseDown={e => { if (e.target === e.currentTarget) handleClose(); }}
    >
      <div className="wa-modal">
        <div className="wa-modal-header">
          <div className="wa-modal-title-row">
            <span className="wa-icon-badge"><MessageCircle size={18} aria-hidden="true" /></span>
            <div>
              <div className="wa-modal-title">{t("plano.wa.title")}</div>
              <div className="wa-modal-sub">{t("plano.wa.subtitle")}</div>
            </div>
          </div>
          <button className="wa-close-btn" onClick={handleClose} aria-label={t("common.close")}>
            <X size={18} aria-hidden="true" />
          </button>
        </div>

        <div className="wa-modal-body">
          <pre className="wa-text-block">{text}</pre>
        </div>

        <div className="wa-modal-footer">
          <button className={`wa-copy-btn${copied ? " copied" : ""}`} onClick={handleCopy}>
            {copied
              ? <><Check size={15} aria-hidden="true" /> {t("common.copied")}</>
              : <><Copy size={15} aria-hidden="true" /> {t("plano.wa.copyText")}</>}
          </button>
        </div>
      </div>
    </div>,
    document.body
  );
}

/**
 * Patient treatment plan sub-page showing the exercise list with drag-to-reorder
 * and a WhatsApp share button.
 *
 * Receives the active patient via `useOutletContext<Paciente>()` provided by
 * `PacienteDetail`. WhatsApp text is generated by {@link buildPlanWhatsAppText}
 * from `src/lib/whatsapp.ts`. Mounted at `/pacientes/:id/plano`.
 *
 * @returns The treatment plan `<div>` with a draggable exercise list, an
 *   add-exercise zone, an observations card, and the WhatsApp modal portal.
 *
 * @example
 * // Rendered at /pacientes/:id/plano
 */
export default function PlanoTratamento() {
  const { t } = useTranslation();
  const paciente = useOutletContext<Paciente>();
  const plano = paciente.planoTratamento;
  const [exercicios, setExercicios] = useState<Exercicio[]>(() =>
    plano ? plano.fases.flatMap(f => f.exercicios) : []
  );
  const [draggingId, setDraggingId] = useState<string | null>(null);
  const [dragOverId, setDragOverId] = useState<string | null>(null);
  const [showWaModal, setShowWaModal] = useState(false);

  if (!plano) {
    return (
      <div className="card" style={{ padding: 40, textAlign: "center", color: "var(--text-secondary)" }}>
        {t("plano.noPlan")}
      </div>
    );
  }

  const draggingIdx = draggingId ? exercicios.findIndex(e => e.id === draggingId) : -1;

  const handleDragStart = (e: React.DragEvent, id: string) => {
    setDraggingId(id);
    e.dataTransfer.effectAllowed = "move";
  };

  const handleDragOver = (e: React.DragEvent, id: string) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = "move";
    if (id !== draggingId) setDragOverId(id);
  };

  const handleDrop = (e: React.DragEvent, targetId: string) => {
    e.preventDefault();
    if (!draggingId || draggingId === targetId) return;
    setExercicios(prev => {
      const list = [...prev];
      const from = list.findIndex(ex => ex.id === draggingId);
      const to = list.findIndex(ex => ex.id === targetId);
      const [item] = list.splice(from, 1);
      list.splice(to, 0, item);
      return list;
    });
    setDraggingId(null);
    setDragOverId(null);
  };

  const handleDragEnd = () => {
    setDraggingId(null);
    setDragOverId(null);
  };

  return (
    <div className="plano-page">
      <div className="plano-header">
        <div>
          <h1>{t("plano.title")}</h1>
          <p className="plano-subtitle">{paciente.nome} · {paciente.condicao}</p>
        </div>
        <div className="plano-actions">
          <button className="btn-outline-sm btn-whatsapp" onClick={() => setShowWaModal(true)}>
            <MessageCircle size={14} aria-hidden="true" /> {t("plano.sendWhatsApp")}
          </button>
          <button className="btn-primary-sm">
            <Plus size={14} aria-hidden="true" /> {t("plano.addFromLibrary")}
          </button>
        </div>
      </div>

      <div className="exercicios-list">
        {exercicios.length === 0 ? (
          <div className="empty-fase">{t("plano.noExercises")}</div>
        ) : (
          exercicios.map((ex, idx) => {
            const isDragging = draggingId === ex.id;
            const isOver = dragOverId === ex.id;
            const lineBefore = isOver && draggingIdx > idx;
            const lineAfter = isOver && draggingIdx < idx;

            return (
              <div key={ex.id} className="ex-row-wrap">
                <div className={`ex-drop-line${lineBefore ? " visible" : ""}`} />
                <div
                  className={`exercicio-row${isDragging ? " ex-dragging" : ""}`}
                  draggable
                  onDragStart={e => handleDragStart(e, ex.id)}
                  onDragOver={e => handleDragOver(e, ex.id)}
                  onDrop={e => handleDrop(e, ex.id)}
                  onDragEnd={handleDragEnd}
                >
                  <span className="ex-drag" aria-label={t("plano.drag")}>
                    <GripVertical size={16} aria-hidden="true" />
                  </span>
                  <div className={`ex-thumb ${ex.temVideo ? "has-video" : "no-video"}`}>
                    {ex.temVideo ? <Play size={18} aria-hidden="true" /> : t("plano.noVideo")}
                  </div>
                  <div className="ex-info">
                    <div className="ex-name-row">
                      <span className="ex-name">{ex.nome}</span>
                      <span
                        className="ex-cat-badge"
                        style={{ background: `${CATEGORIA_COLORS[ex.categoria] ?? "#888"}20`, color: CATEGORIA_COLORS[ex.categoria] ?? "#888" }}
                      >
                        {ex.categoria}
                      </span>
                    </div>
                    <div className="ex-series">{t("plano.series", { count: ex.series })}</div>
                  </div>
                  <div className="ex-actions">
                    <button className="ex-btn" aria-label={t("plano.edit")}>
                      <Pencil size={14} aria-hidden="true" />
                    </button>
                    <button className="ex-btn ex-btn-del" aria-label={t("plano.delete")}>
                      <Trash2 size={14} aria-hidden="true" />
                    </button>
                  </div>
                </div>
                <div className={`ex-drop-line${lineAfter ? " visible" : ""}`} />
              </div>
            );
          })
        )}
      </div>

      <div className="add-exercise-zone" aria-label={t("plano.dragZone")}>
        <Plus size={20} aria-hidden="true" />
        <span>{t("plano.dragZone")}</span>
      </div>

      <div className="card observacoes-card">
        <h2>{t("plano.observations")}</h2>
        <blockquote className="obs-text">{plano.observacoes}</blockquote>
      </div>

      {showWaModal && (
        <WhatsAppModal
          paciente={paciente}
          exercicios={exercicios}
          onClose={() => setShowWaModal(false)}
        />
      )}
    </div>
  );
}
